--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster-app
  region: us-east-1

nodeGroups:
  - name: demo-ng-public
    instanceType: t3.medium
    desiredCapacity: 2
  
managedNodeGroups:
  - name: demo-ng-managed
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 2